
export const actionTypes = {
	ADD_TO_BASKET : 'ADD_TO_BASKET',
	INCREASE_GOOD : 'INCREASE_GOOD',
	DECREASE_GOOD : 'DECREASE_GOOD',
	DELETE_GOOD : 'DELETE_GOOD',
	CLEAR_THE_BASKET : 'CLEAR_THE_BASKET',
	MAKE_THE_ORDER : 'MAKE_THE_ORDER',

	LOG_IN : 'LOG_IN',
	LOG_OUT : 'LOG_OUT'
}